[entryPoints]
  [entryPoints.http]
    address = "10.1.12.25:8080"
  [entryPoints.traefik]
    address = "10.1.12.25:9002"

logLevel="INFO"
[traefikLog]
  filePath = "/var/log/traefik.log"
[accessLog]
  filePath = "/var/log/traefik-access.log"

[api]
  dashboard = true
[consulcatalog]
  endpoint = "10.1.12.25:8500"
  stale = false
  exposedByDefault = true
  frontEndRule = "Host:{{ .ServiceName }}.minipot"
